namespace: logging
resources:
- ../base/fluent-bit-configmap.yaml
patches:
- target:
    kind: ConfigMap
    name: fluent-bit-config
  patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: fluent-bit-config
      namespace: fluent-bit
      labels:
        k8s-app: fluent-bit
    data:
      fluent-bit.conf: |
        [SERVICE]
            Flush         1
            Log_Level     info
            Daemon        off
            Parsers_File  parsers.conf
            HTTP_Server   On
            HTTP_Listen   0.0.0.0
            HTTP_Port     2050
