apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluent-bit
data:
  input-kubernetes.conf: |
    [INPUT]
      Name              tail
      Tag               kube.*
      Path              /var/log/containers/*.log
      Exclude_Path      /var/log/containers/*_logging_*.log
      Parser            docker
      DB                /var/log/flb_kube.db
      Mem_Buf_Limit     50MB
      Skip_Long_Lines   On
      Refresh_Interval  10
  output-elasticsearch.conf: |
    [OUTPUT]
      Name            es
      Match           *
      Host            ${FLUENT_ELASTICSEARCH_HOST}
      Port            ${FLUENT_ELASTICSEARCH_PORT}
      TLS             On
      AWS_Auth        On
      AWS_Region      us-west-2
      Retry_Limit     6
      Logstash_Format On
      Logstash_Prefix fluent-bit
      Replace_Dots    On
